version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout

      - run: npm install; npm run ng build

      - persist_to_workspace:
          root: ~/project
          paths:
            - dist

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - add_ssh_keys:
          fingerprints:
            - "37:f2:a9:05:d7:9d:42:f4:d8:57:6b:3d:82:60:d3:41"

      - run:
          name: Deploy Over SSH
          command: |
            cp ~/project/.circleci/known_hosts ~/.ssh/
            git config --global user.email "oldbroth3rz@gmail.com"
            git config --global user.name "Oldbroth3rz"
            git add .
            git commit -m 'Add dist folder'
            git status
            git remote add production ssh://${USER_NAME}@${HOSTNAME}/var/repo/lebonapp.git
            git push --force production master
            exit
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
